package tokens

type TokenType int

const (
    TOKEN_ERROR TokenType = iota
    TOKEN_EOF

    TOKEN_LEFT_BRACKET
    TOKEN_RIGHT_BRACKET
    TOKEN_LEFT_CURLY_BRACKET
    TOKEN_RIGHT_CURLY_BRACKET
    TOKEN_COLON
    TOKEN_COMMAS
    TOKEN_DOBLE_QUOTES
    TOKEN_NUMBERS
    TOKEN_BOOLEAN_TRUE
    TOKEN_BOOLEAN_FALSE
    TOKEN_NULL
    TOKEN_NEWLINE

    TOKEN_SECTION
    TOKEN_KEY
    TOKEN_VALUE
)

